[project]
name = "stacks-guild"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.guild-nft]
path = "contracts/guild-nft.clar"

[contracts.guild-system]
path = "contracts/guild-system.clar"

[contracts.sip009-trait]
path = "contracts/sip009-trait.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
